# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.23)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS TKernel TKMath TKG2d TKG3d TKGeomBase TKBRep TKGeomAlgo TKTopAlgo TKPrim TKBO TKShHealing TKBool TKHLR TKFillet TKOffset TKFeat TKMesh TKXMesh TKService TKV3d TKOpenGl TKMeshVS TKCDF TKLCAF TKCAF TKBinL TKXmlL TKBin TKXml TKStdL TKStd TKTObj TKBinTObj TKXmlTObj TKVCAF TKXSBase TKSTEPBase TKSTEPAttr TKSTEP209 TKSTEP TKIGES TKXCAF TKXDEIGES TKXDESTEP TKSTL TKVRML TKXmlXCAF TKBinXCAF TKRWMesh)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target TKernel
add_library(TKernel SHARED IMPORTED)

set_target_properties(TKernel PROPERTIES
  INTERFACE_LINK_LIBRARIES "pthread;rt;stdc++;dl"
)

# Create imported target TKMath
add_library(TKMath SHARED IMPORTED)

set_target_properties(TKMath PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel"
)

# Create imported target TKG2d
add_library(TKG2d SHARED IMPORTED)

set_target_properties(TKG2d PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKMath"
)

# Create imported target TKG3d
add_library(TKG3d SHARED IMPORTED)

set_target_properties(TKG3d PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKMath;TKernel;TKG2d"
)

# Create imported target TKGeomBase
add_library(TKGeomBase SHARED IMPORTED)

set_target_properties(TKGeomBase PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKMath;TKG2d;TKG3d"
)

# Create imported target TKBRep
add_library(TKBRep SHARED IMPORTED)

set_target_properties(TKBRep PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKMath;TKernel;TKG2d;TKG3d;TKGeomBase"
)

# Create imported target TKGeomAlgo
add_library(TKGeomAlgo SHARED IMPORTED)

set_target_properties(TKGeomAlgo PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKMath;TKG3d;TKG2d;TKGeomBase;TKBRep"
)

# Create imported target TKTopAlgo
add_library(TKTopAlgo SHARED IMPORTED)

set_target_properties(TKTopAlgo PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKMath;TKernel;TKG2d;TKG3d;TKGeomBase;TKBRep;TKGeomAlgo"
)

# Create imported target TKPrim
add_library(TKPrim SHARED IMPORTED)

set_target_properties(TKPrim PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKernel;TKMath;TKG2d;TKGeomBase;TKG3d;TKTopAlgo"
)

# Create imported target TKBO
add_library(TKBO SHARED IMPORTED)

set_target_properties(TKBO PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKTopAlgo;TKMath;TKernel;TKG2d;TKG3d;TKGeomAlgo;TKGeomBase;TKPrim;TKShHealing"
)

# Create imported target TKShHealing
add_library(TKShHealing SHARED IMPORTED)

set_target_properties(TKShHealing PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKernel;TKMath;TKG2d;TKTopAlgo;TKG3d;TKGeomBase;TKGeomAlgo"
)

# Create imported target TKBool
add_library(TKBool SHARED IMPORTED)

set_target_properties(TKBool PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKTopAlgo;TKMath;TKernel;TKPrim;TKG2d;TKG3d;TKShHealing;TKGeomBase;TKGeomAlgo;TKBO"
)

# Create imported target TKHLR
add_library(TKHLR SHARED IMPORTED)

set_target_properties(TKHLR PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKernel;TKMath;TKGeomBase;TKG2d;TKG3d;TKGeomAlgo;TKTopAlgo"
)

# Create imported target TKFillet
add_library(TKFillet SHARED IMPORTED)

set_target_properties(TKFillet PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKernel;TKMath;TKGeomBase;TKGeomAlgo;TKG2d;TKTopAlgo;TKG3d;TKBool;TKShHealing;TKBO"
)

# Create imported target TKOffset
add_library(TKOffset SHARED IMPORTED)

set_target_properties(TKOffset PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKFillet;TKBRep;TKTopAlgo;TKMath;TKernel;TKGeomBase;TKG2d;TKG3d;TKGeomAlgo;TKShHealing;TKBO;TKPrim;TKBool"
)

# Create imported target TKFeat
add_library(TKFeat SHARED IMPORTED)

set_target_properties(TKFeat PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKTopAlgo;TKGeomAlgo;TKMath;TKernel;TKGeomBase;TKPrim;TKG2d;TKBO;TKG3d;TKBool;TKShHealing"
)

# Create imported target TKMesh
add_library(TKMesh SHARED IMPORTED)

set_target_properties(TKMesh PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKMath;TKBRep;TKTopAlgo;TKShHealing;TKGeomBase;TKG3d;TKG2d"
)

# Create imported target TKXMesh
add_library(TKXMesh SHARED IMPORTED)

set_target_properties(TKXMesh PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKMath;TKernel;TKG2d;TKG3d;TKMesh"
)

# Create imported target TKService
add_library(TKService SHARED IMPORTED)

set_target_properties(TKService PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKMath;X11;fontconfig;/usr/lib64/libfreetype.so"
)

# Create imported target TKV3d
add_library(TKV3d SHARED IMPORTED)

set_target_properties(TKV3d PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKMath;TKernel;TKService;TKShHealing;TKTopAlgo;TKG2d;TKG3d;TKGeomBase;TKMesh;TKGeomAlgo;TKHLR;GL;X11;/usr/lib64/libfreetype.so"
)

# Create imported target TKOpenGl
add_library(TKOpenGl SHARED IMPORTED)

set_target_properties(TKOpenGl PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKService;TKMath;GL;X11"
)

# Create imported target TKMeshVS
add_library(TKMeshVS SHARED IMPORTED)

set_target_properties(TKMeshVS PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKV3d;TKMath;TKService;TKernel;TKG3d;TKG2d"
)

# Create imported target TKCDF
add_library(TKCDF SHARED IMPORTED)

set_target_properties(TKCDF PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel"
)

# Create imported target TKLCAF
add_library(TKLCAF SHARED IMPORTED)

set_target_properties(TKLCAF PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKCDF;TKernel"
)

# Create imported target TKCAF
add_library(TKCAF SHARED IMPORTED)

set_target_properties(TKCAF PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKGeomBase;TKBRep;TKTopAlgo;TKMath;TKG2d;TKG3d;TKCDF;TKLCAF;TKBO"
)

# Create imported target TKBinL
add_library(TKBinL SHARED IMPORTED)

set_target_properties(TKBinL PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKCDF;TKernel;TKLCAF"
)

# Create imported target TKXmlL
add_library(TKXmlL SHARED IMPORTED)

set_target_properties(TKXmlL PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKCDF;TKernel;TKMath;TKLCAF"
)

# Create imported target TKBin
add_library(TKBin SHARED IMPORTED)

set_target_properties(TKBin PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKMath;TKernel;TKG2d;TKG3d;TKCAF;TKCDF;TKLCAF;TKBinL"
)

# Create imported target TKXml
add_library(TKXml SHARED IMPORTED)

set_target_properties(TKXml PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKCDF;TKernel;TKMath;TKBRep;TKG2d;TKGeomBase;TKG3d;TKLCAF;TKCAF;TKXmlL"
)

# Create imported target TKStdL
add_library(TKStdL SHARED IMPORTED)

set_target_properties(TKStdL PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKCDF;TKLCAF"
)

# Create imported target TKStd
add_library(TKStd SHARED IMPORTED)

set_target_properties(TKStd PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKCDF;TKCAF;TKLCAF;TKBRep;TKMath;TKG2d;TKG3d;TKStdL"
)

# Create imported target TKTObj
add_library(TKTObj SHARED IMPORTED)

set_target_properties(TKTObj PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKCDF;TKernel;TKMath;TKLCAF"
)

# Create imported target TKBinTObj
add_library(TKBinTObj SHARED IMPORTED)

set_target_properties(TKBinTObj PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKCDF;TKernel;TKTObj;TKMath;TKLCAF;TKBinL"
)

# Create imported target TKXmlTObj
add_library(TKXmlTObj SHARED IMPORTED)

set_target_properties(TKXmlTObj PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKCDF;TKernel;TKTObj;TKMath;TKLCAF;TKXmlL"
)

# Create imported target TKVCAF
add_library(TKVCAF SHARED IMPORTED)

set_target_properties(TKVCAF PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKGeomBase;TKBRep;TKTopAlgo;TKMath;TKService;TKG2d;TKG3d;TKCDF;TKLCAF;TKBO;TKCAF;TKV3d"
)

# Create imported target TKXSBase
add_library(TKXSBase SHARED IMPORTED)

set_target_properties(TKXSBase PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKernel;TKMath;TKG2d;TKG3d;TKTopAlgo;TKGeomBase;TKShHealing"
)

# Create imported target TKSTEPBase
add_library(TKSTEPBase SHARED IMPORTED)

set_target_properties(TKSTEPBase PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKXSBase;TKMath"
)

# Create imported target TKSTEPAttr
add_library(TKSTEPAttr SHARED IMPORTED)

set_target_properties(TKSTEPAttr PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKXSBase;TKSTEPBase"
)

# Create imported target TKSTEP209
add_library(TKSTEP209 SHARED IMPORTED)

set_target_properties(TKSTEP209 PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKXSBase;TKSTEPBase"
)

# Create imported target TKSTEP
add_library(TKSTEP SHARED IMPORTED)

set_target_properties(TKSTEP PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKSTEPAttr;TKSTEP209;TKSTEPBase;TKBRep;TKMath;TKG2d;TKShHealing;TKTopAlgo;TKG3d;TKGeomBase;TKGeomAlgo;TKXSBase"
)

# Create imported target TKIGES
add_library(TKIGES SHARED IMPORTED)

set_target_properties(TKIGES PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKernel;TKMath;TKTopAlgo;TKShHealing;TKG2d;TKG3d;TKGeomBase;TKGeomAlgo;TKPrim;TKBool;TKXSBase"
)

# Create imported target TKXCAF
add_library(TKXCAF SHARED IMPORTED)

set_target_properties(TKXCAF PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKernel;TKMath;TKService;TKG2d;TKTopAlgo;TKV3d;TKCDF;TKLCAF;TKG3d;TKCAF;TKVCAF"
)

# Create imported target TKXDEIGES
add_library(TKXDEIGES SHARED IMPORTED)

set_target_properties(TKXDEIGES PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKernel;TKMath;TKXSBase;TKCDF;TKLCAF;TKG2d;TKG3d;TKXCAF;TKIGES"
)

# Create imported target TKXDESTEP
add_library(TKXDESTEP SHARED IMPORTED)

set_target_properties(TKXDESTEP PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKSTEPAttr;TKernel;TKMath;TKXSBase;TKTopAlgo;TKG2d;TKCAF;TKSTEPBase;TKCDF;TKLCAF;TKG3d;TKXCAF;TKSTEP;TKShHealing"
)

# Create imported target TKSTL
add_library(TKSTL SHARED IMPORTED)

set_target_properties(TKSTL PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKMath;TKBRep;TKG2d;TKG3d;TKTopAlgo"
)

# Create imported target TKVRML
add_library(TKVRML SHARED IMPORTED)

set_target_properties(TKVRML PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKTopAlgo;TKMath;TKGeomBase;TKernel;TKPrim;TKG2d;TKG3d;TKMesh;TKHLR;TKService;TKGeomAlgo;TKV3d;TKLCAF;TKXCAF"
)

# Create imported target TKXmlXCAF
add_library(TKXmlXCAF SHARED IMPORTED)

set_target_properties(TKXmlXCAF PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKXmlL;TKBRep;TKCDF;TKMath;TKernel;TKService;TKG2d;TKGeomBase;TKCAF;TKG3d;TKLCAF;TKXCAF;TKXml"
)

# Create imported target TKBinXCAF
add_library(TKBinXCAF SHARED IMPORTED)

set_target_properties(TKBinXCAF PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKBRep;TKXCAF;TKMath;TKService;TKernel;TKBinL;TKG2d;TKCAF;TKCDF;TKG3d;TKLCAF;TKBin"
)

# Create imported target TKRWMesh
add_library(TKRWMesh SHARED IMPORTED)

set_target_properties(TKRWMesh PROPERTIES
  INTERFACE_LINK_LIBRARIES "TKernel;TKMath;TKMesh;TKXCAF;TKLCAF;TKV3d;TKBRep;TKG3d;TKService"
)

# Import target "TKernel" for configuration "Release"
set_property(TARGET TKernel APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKernel PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKernel.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKernel.so.7"
  )

# Import target "TKMath" for configuration "Release"
set_property(TARGET TKMath APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKMath PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKMath.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKMath.so.7"
  )

# Import target "TKG2d" for configuration "Release"
set_property(TARGET TKG2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKG2d PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKG2d.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKG2d.so.7"
  )

# Import target "TKG3d" for configuration "Release"
set_property(TARGET TKG3d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKG3d PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKG3d.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKG3d.so.7"
  )

# Import target "TKGeomBase" for configuration "Release"
set_property(TARGET TKGeomBase APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKGeomBase PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKGeomBase.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKGeomBase.so.7"
  )

# Import target "TKBRep" for configuration "Release"
set_property(TARGET TKBRep APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBRep PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKBRep.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKBRep.so.7"
  )

# Import target "TKGeomAlgo" for configuration "Release"
set_property(TARGET TKGeomAlgo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKGeomAlgo PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKGeomAlgo.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKGeomAlgo.so.7"
  )

# Import target "TKTopAlgo" for configuration "Release"
set_property(TARGET TKTopAlgo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKTopAlgo PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKTopAlgo.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKTopAlgo.so.7"
  )

# Import target "TKPrim" for configuration "Release"
set_property(TARGET TKPrim APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKPrim PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKPrim.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKPrim.so.7"
  )

# Import target "TKBO" for configuration "Release"
set_property(TARGET TKBO APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBO PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKBO.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKBO.so.7"
  )

# Import target "TKShHealing" for configuration "Release"
set_property(TARGET TKShHealing APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKShHealing PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKShHealing.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKShHealing.so.7"
  )

# Import target "TKBool" for configuration "Release"
set_property(TARGET TKBool APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBool PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKBool.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKBool.so.7"
  )

# Import target "TKHLR" for configuration "Release"
set_property(TARGET TKHLR APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKHLR PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKHLR.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKHLR.so.7"
  )

# Import target "TKFillet" for configuration "Release"
set_property(TARGET TKFillet APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKFillet PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKFillet.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKFillet.so.7"
  )

# Import target "TKOffset" for configuration "Release"
set_property(TARGET TKOffset APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKOffset PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKOffset.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKOffset.so.7"
  )

# Import target "TKFeat" for configuration "Release"
set_property(TARGET TKFeat APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKFeat PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKFeat.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKFeat.so.7"
  )

# Import target "TKMesh" for configuration "Release"
set_property(TARGET TKMesh APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKMesh PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKMesh.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKMesh.so.7"
  )

# Import target "TKXMesh" for configuration "Release"
set_property(TARGET TKXMesh APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXMesh PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKXMesh.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKXMesh.so.7"
  )

# Import target "TKService" for configuration "Release"
set_property(TARGET TKService APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKService PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKService.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKService.so.7"
  )

# Import target "TKV3d" for configuration "Release"
set_property(TARGET TKV3d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKV3d PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKV3d.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKV3d.so.7"
  )

# Import target "TKOpenGl" for configuration "Release"
set_property(TARGET TKOpenGl APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKOpenGl PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKOpenGl.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKOpenGl.so.7"
  )

# Import target "TKMeshVS" for configuration "Release"
set_property(TARGET TKMeshVS APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKMeshVS PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKMeshVS.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKMeshVS.so.7"
  )

# Import target "TKCDF" for configuration "Release"
set_property(TARGET TKCDF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKCDF PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKCDF.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKCDF.so.7"
  )

# Import target "TKLCAF" for configuration "Release"
set_property(TARGET TKLCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKLCAF PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKLCAF.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKLCAF.so.7"
  )

# Import target "TKCAF" for configuration "Release"
set_property(TARGET TKCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKCAF PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKCAF.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKCAF.so.7"
  )

# Import target "TKBinL" for configuration "Release"
set_property(TARGET TKBinL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBinL PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKBinL.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKBinL.so.7"
  )

# Import target "TKXmlL" for configuration "Release"
set_property(TARGET TKXmlL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXmlL PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKXmlL.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKXmlL.so.7"
  )

# Import target "TKBin" for configuration "Release"
set_property(TARGET TKBin APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBin PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKBin.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKBin.so.7"
  )

# Import target "TKXml" for configuration "Release"
set_property(TARGET TKXml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXml PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKXml.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKXml.so.7"
  )

# Import target "TKStdL" for configuration "Release"
set_property(TARGET TKStdL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKStdL PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKStdL.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKStdL.so.7"
  )

# Import target "TKStd" for configuration "Release"
set_property(TARGET TKStd APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKStd PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKStd.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKStd.so.7"
  )

# Import target "TKTObj" for configuration "Release"
set_property(TARGET TKTObj APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKTObj PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKTObj.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKTObj.so.7"
  )

# Import target "TKBinTObj" for configuration "Release"
set_property(TARGET TKBinTObj APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBinTObj PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKBinTObj.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKBinTObj.so.7"
  )

# Import target "TKXmlTObj" for configuration "Release"
set_property(TARGET TKXmlTObj APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXmlTObj PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKXmlTObj.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKXmlTObj.so.7"
  )

# Import target "TKVCAF" for configuration "Release"
set_property(TARGET TKVCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKVCAF PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKVCAF.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKVCAF.so.7"
  )

# Import target "TKXSBase" for configuration "Release"
set_property(TARGET TKXSBase APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXSBase PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKXSBase.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKXSBase.so.7"
  )

# Import target "TKSTEPBase" for configuration "Release"
set_property(TARGET TKSTEPBase APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKSTEPBase PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKSTEPBase.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKSTEPBase.so.7"
  )

# Import target "TKSTEPAttr" for configuration "Release"
set_property(TARGET TKSTEPAttr APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKSTEPAttr PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKSTEPAttr.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKSTEPAttr.so.7"
  )

# Import target "TKSTEP209" for configuration "Release"
set_property(TARGET TKSTEP209 APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKSTEP209 PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKSTEP209.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKSTEP209.so.7"
  )

# Import target "TKSTEP" for configuration "Release"
set_property(TARGET TKSTEP APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKSTEP PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKSTEP.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKSTEP.so.7"
  )

# Import target "TKIGES" for configuration "Release"
set_property(TARGET TKIGES APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKIGES PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKIGES.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKIGES.so.7"
  )

# Import target "TKXCAF" for configuration "Release"
set_property(TARGET TKXCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXCAF PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKXCAF.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKXCAF.so.7"
  )

# Import target "TKXDEIGES" for configuration "Release"
set_property(TARGET TKXDEIGES APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXDEIGES PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKXDEIGES.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKXDEIGES.so.7"
  )

# Import target "TKXDESTEP" for configuration "Release"
set_property(TARGET TKXDESTEP APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXDESTEP PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKXDESTEP.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKXDESTEP.so.7"
  )

# Import target "TKSTL" for configuration "Release"
set_property(TARGET TKSTL APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKSTL PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKSTL.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKSTL.so.7"
  )

# Import target "TKVRML" for configuration "Release"
set_property(TARGET TKVRML APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKVRML PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKVRML.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKVRML.so.7"
  )

# Import target "TKXmlXCAF" for configuration "Release"
set_property(TARGET TKXmlXCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKXmlXCAF PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKXmlXCAF.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKXmlXCAF.so.7"
  )

# Import target "TKBinXCAF" for configuration "Release"
set_property(TARGET TKBinXCAF APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKBinXCAF PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKBinXCAF.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKBinXCAF.so.7"
  )

# Import target "TKRWMesh" for configuration "Release"
set_property(TARGET TKRWMesh APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(TKRWMesh PROPERTIES
  IMPORTED_LOCATION_RELEASE "/home/sugardaddy/Downloads/OCCT1VERSION/lin64/gcc/lib/libTKRWMesh.so.7.6.3"
  IMPORTED_SONAME_RELEASE "libTKRWMesh.so.7"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
